# Generated by Django 5.2 on 2025-07-29 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم گیم')),
                ('img', models.ImageField(blank=True, null=True, upload_to='producr_img/', verbose_name='عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال یا غیرفعال؟')),
                ('is_delete', models.BooleanField(default=False, verbose_name='اره یا نا؟')),
                ('price', models.IntegerField(db_index=True, default=0, verbose_name='قیمت')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح کامل')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='url عنوان در ')),
                ('off', models.IntegerField(db_index=True, default=0, verbose_name='تخفیف')),
                ('is_off', models.BooleanField(default=False, verbose_name='فعال یا غیرفعال؟تخفیف')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='url عنوان در')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال یا غیرفعال؟')),
                ('is_delete', models.BooleanField(default=False, verbose_name='اره یا نا؟')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentcategories', to='product_module.productcategory')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
    ]
