# Generated by Django 5.2 on 2025-07-31 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_remove_product_img_product_image_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_module.category'),
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(max_length=50, verbose_name='سایز\u200cها (S,M,L,XL)')),
                ('colors', models.CharField(max_length=200, verbose_name='رنگ\u200cهای موجود')),
                ('fabric', models.CharField(blank=True, max_length=100, null=True, verbose_name='جنس پارچه')),
                ('clothing_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع لباس (تی\u200cشرت، شلوار...)')),
                ('gender', models.CharField(blank=True, choices=[('men', 'مردانه'), ('women', 'زنانه'), ('unisex', 'یونیسکس')], max_length=20, null=True, verbose_name='جنسیت')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing', to='product_module.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(max_length=100, verbose_name='سایزها (مثال: 40,41,42)')),
                ('colors', models.CharField(max_length=200, verbose_name='رنگ\u200cهای موجود')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='جنس رویه')),
                ('sole_material', models.CharField(blank=True, max_length=100, null=True, verbose_name='جنس کفی')),
                ('shoe_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع کفش (دویدن، فوتبال، سالنی...)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='وزن (کیلوگرم)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoe', to='product_module.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
