# Generated by Django 5.2 on 2025-07-31 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothing',
            options={'verbose_name': 'لباس ورزشی', 'verbose_name_plural': 'لباس\u200cهای ورزشی'},
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='sizes',
        ),
        migrations.AddField(
            model_name='clothing',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='clothing_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع لباس'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing', to='product_module.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_module.category', verbose_name='کتگوری'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='پاک بشه یا نا؟'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_type', models.CharField(max_length=50, verbose_name='نوع لوازم جانبی')),
                ('material', models.CharField(max_length=50, verbose_name='جنس')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='سایز / ابعاد')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'لوازم جانبی',
                'verbose_name_plural': 'لوازم جانبی',
            },
        ),
        migrations.CreateModel(
            name='GameEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع وسیله بازی')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='سایز')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='وزن')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='جنس')),
                ('usage', models.CharField(blank=True, max_length=50, null=True, verbose_name='محیط استفاده')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_equipment', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'وسایل بازی',
                'verbose_name_plural': 'توپ و وسایل بازی',
            },
        ),
        migrations.CreateModel(
            name='GymEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='وزن')),
                ('dimensions', models.CharField(max_length=100, verbose_name='ابعاد (طول×عرض×ارتفاع)')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('body_material', models.CharField(max_length=100, verbose_name='جنس بدنه')),
                ('equipment_type', models.CharField(max_length=50, verbose_name='نوع وسیله')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym_equipment', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'لوازم فیتنس',
                'verbose_name_plural': 'لوازم باشگاهی و فیتنس',
            },
        ),
        migrations.CreateModel(
            name='ProtectiveGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_type', models.CharField(max_length=50, verbose_name='نوع تجهیزات ایمنی')),
                ('size', models.CharField(max_length=20, verbose_name='سایز')),
                ('material', models.CharField(max_length=50, verbose_name='جنس')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protective_gear', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تجهیزات ایمنی',
                'verbose_name_plural': 'تجهیزات محافظتی و ایمنی',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_sizes', models.CharField(max_length=100, verbose_name='سایزهای موجود')),
                ('available_colors', models.CharField(max_length=100, verbose_name='رنگ\u200cهای موجود')),
                ('upper_material', models.CharField(max_length=100, verbose_name='جنس رویه')),
                ('sole_material', models.CharField(max_length=100, verbose_name='جنس کفی')),
                ('shoe_type', models.CharField(max_length=50, verbose_name='نوع کفش')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='وزن (کیلوگرم)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'کفش ورزشی',
                'verbose_name_plural': 'کفش\u200cهای ورزشی',
            },
        ),
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_volume', models.CharField(max_length=50, verbose_name='وزن / حجم بسته')),
                ('flavor', models.CharField(max_length=50, verbose_name='طعم')),
                ('expiration_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('ingredients', models.TextField(verbose_name='ترکیبات اصلی')),
                ('brand', models.CharField(max_length=100, verbose_name='برند')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مکمل',
                'verbose_name_plural': 'مکمل\u200cها',
            },
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
