# Generated by Django 5.2 on 2025-07-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_alter_clothing_options_remove_clothing_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال یا غیرفعال؟'),
        ),
    ]
