# Generated by Django 5.2 on 2025-07-31 22:08

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_alter_subcategory_options_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='available_colors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('white', 'سفید'), ('black', 'مشکی'), ('blue', 'آبی'), ('red', 'قرمز'), ('green', 'سبز')], max_length=50, verbose_name='رنگ\u200cهای موجود'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='available_sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('40', '۴۰'), ('41', '۴۱'), ('42', '۴۲'), ('43', '۴۳'), ('44', '۴۴'), ('45', '۴۵')], max_length=20, verbose_name='سایزهای موجود'),
        ),
    ]
