# Generated by Django 5.2 on 2025-07-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_alter_shoes_available_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='shoe_type',
            field=models.CharField(choices=[('running', 'دویدن'), ('indoor', 'سالنی'), ('football', 'فوتبال'), ('basketball', 'بسکتبال'), ('all', 'همه\u200cکاره')], max_length=50, verbose_name='نوع کفش'),
        ),
    ]
