# Generated by Django 5.2 on 2025-07-31 22:19

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_alter_shoes_shoe_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='color',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='size',
        ),
        migrations.AddField(
            model_name='clothing',
            name='colors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('سفید', 'سفید'), ('مشکی', 'مشکی'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('سبز', 'سبز')], default='', max_length=22, null=True, verbose_name='رنگ\u200cهای موجود'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='fabric_material',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('پنبه', 'پنبه'), ('پلی\u200cاستر', 'پلی\u200cاستر'), ('کتان', 'کتان'), ('نایلون', 'نایلون')], default='', max_length=25, null=True, verbose_name='جنس پارچه'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='', max_length=12, null=True, verbose_name='سایزهای موجود'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='clothing_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('تی\u200cشرت', 'تی\u200cشرت'), ('شلوار', 'شلوار'), ('سوییشرت', 'سوییشرت'), ('ست', 'ست')], default='', max_length=23, null=True, verbose_name='نوع لباس'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('مردانه', 'مردانه'), ('زنانه', 'زنانه'), ('یونیسکس', 'یونیسکس')], default='', max_length=20, null=True, verbose_name='جنسیت'),
        ),
    ]
