# Generated by Django 5.2 on 2025-07-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_remove_clothing_color_remove_clothing_fabric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='color',
            field=models.CharField(choices=[('سفید', 'سفید'), ('مشکی', 'مشکی'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('سبز', 'سبز')], max_length=50, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='gymequipment',
            name='color',
            field=models.CharField(choices=[('سفید', 'سفید'), ('مشکی', 'مشکی'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('سبز', 'سبز')], max_length=50, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='protectivegear',
            name='color',
            field=models.CharField(choices=[('سفید', 'سفید'), ('مشکی', 'مشکی'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('سبز', 'سبز')], max_length=50, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='protectivegear',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='weight_volume',
            field=models.CharField(max_length=50, verbose_name='(کیلو گرم)وزن / حجم بسته'),
        ),
    ]
