# Generated by Django 5.2 on 2025-07-31 22:28

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_alter_accessories_color_alter_gymequipment_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymequipment',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('سفید', 'سفید'), ('مشکی', 'مشکی'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('سبز', 'سبز')], max_length=50, verbose_name='رنگ'),
        ),
    ]
