# Generated by Django 5.2 on 2025-07-31 22:29

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0014_alter_gymequipment_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('سفید', 'سفید'), ('مشکی', 'مشکی'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('سبز', 'سبز')], max_length=50, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='protectivegear',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('سفید', 'سفید'), ('مشکی', 'مشکی'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('سبز', 'سبز')], max_length=50, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='protectivegear',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, verbose_name='سایز'),
        ),
    ]
