# Generated by Django 5.2 on 2025-08-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_alter_accessories_color_alter_protectivegear_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'زیر دسته\u200c', 'verbose_name_plural': 'زیر دسته\u200c'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='عکس ها'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال یا غیرفعال؟'),
        ),
    ]
