# Generated by Django 5.2 on 2025-08-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0018_product_image5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
    ]
