# Generated by Django 5.2 on 2025-08-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0019_remove_product_image5'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='clothing',
            name='clothing_type',
            field=models.CharField(blank=True, choices=[('تی\u200cشرت', 'تی\u200cشرت'), ('شلوار', 'شلوار'), ('سوییشرت', 'سوییشرت'), ('ست', 'ست')], default='', null=True, verbose_name='نوع لباس'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='fabric_material',
            field=models.CharField(blank=True, choices=[('پنبه', 'پنبه'), ('پلی\u200cاستر', 'پلی\u200cاستر'), ('کتان', 'کتان'), ('نایلون', 'نایلون')], default='', null=True, verbose_name='جنس پارچه'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='gender',
            field=models.CharField(blank=True, choices=[('مردانه', 'مردانه'), ('زنانه', 'زنانه'), ('یونیسکس', 'یونیسکس')], default='', null=True, verbose_name='جنسیت'),
        ),
    ]
