# Generated by Django 5.2 on 2025-08-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0020_color_alter_clothing_clothing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='available_colors',
        ),
        migrations.AddField(
            model_name='shoes',
            name='available_colors',
            field=models.ManyToManyField(to='product_module.color', verbose_name='رنگ\u200cهای موجود'),
        ),
    ]
