# Generated by Django 5.2 on 2025-08-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0021_remove_shoes_available_colors_shoes_available_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='available_sizes',
        ),
        migrations.AddField(
            model_name='shoes',
            name='available_sizes',
            field=models.ManyToManyField(max_length=20, to='product_module.sizes', verbose_name='سایزهای موجود'),
        ),
    ]
