# Generated by Django 5.2 on 2025-08-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0022_sizes_remove_shoes_available_sizes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sizes',
            new_name='shosesizes',
        ),
    ]
