# Generated by Django 5.2 on 2025-08-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0023_rename_sizes_shosesizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothingsizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='sizes',
        ),
        migrations.AddField(
            model_name='clothing',
            name='colors',
            field=models.ManyToManyField(blank=True, default='', null=True, to='product_module.color', verbose_name='رنگ\u200cهای موجود'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='sizes',
            field=models.ManyToManyField(blank=True, default='', null=True, to='product_module.clothingsizes', verbose_name='سایزهای موجود'),
        ),
    ]
