# Generated by Django 5.2 on 2025-08-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0024_clothingsizes_remove_clothing_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothingfabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='fabric_material',
        ),
        migrations.AddField(
            model_name='clothing',
            name='fabric_material',
            field=models.ManyToManyField(blank=True, default='', null=True, to='product_module.clothingfabric', verbose_name='جنس پارچه'),
        ),
    ]
