# Generated by Django 5.2 on 2025-08-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0025_clothingfabric_remove_clothing_fabric_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='color',
        ),
        migrations.RemoveField(
            model_name='gymequipment',
            name='color',
        ),
        migrations.RemoveField(
            model_name='protectivegear',
            name='color',
        ),
        migrations.RemoveField(
            model_name='protectivegear',
            name='size',
        ),
        migrations.AddField(
            model_name='accessories',
            name='color',
            field=models.ManyToManyField(max_length=50, to='product_module.color', verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='gymequipment',
            name='color',
            field=models.ManyToManyField(max_length=50, to='product_module.color', verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='protectivegear',
            name='color',
            field=models.ManyToManyField(max_length=50, to='product_module.color', verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='protectivegear',
            name='size',
            field=models.ManyToManyField(max_length=20, to='product_module.clothingsizes', verbose_name='سایز'),
        ),
    ]
