# Generated by Django 5.2 on 2025-08-09 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0026_remove_accessories_color_remove_gymequipment_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_percent',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف تومان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.IntegerField(db_index=True, default=0, verbose_name='تخفیف تومان'),
        ),
    ]
