# Generated by Django 5.2 on 2025-08-09 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0027_product_off_percent_alter_product_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='تخفیف تومان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_percent',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف درصد'),
        ),
    ]
