# Generated by Django 5.2 on 2025-08-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0028_alter_product_off_alter_product_off_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='off',
        ),
    ]
