# Generated by Django 5.2 on 2025-09-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0031_favorite_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
