# Generated by Django 5.2 on 2025-09-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0032_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='today',
            field=models.BooleanField(default=False, verbose_name='ارسال امروز'),
        ),
    ]
