# Generated by Django 5.2 on 2025-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0033_product_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=False, verbose_name='محصولات پرفروش '),
        ),
        migrations.AddField(
            model_name='product',
            name='hot',
            field=models.BooleanField(default=False, verbose_name=' داغ ترین چند ساعت گذشته'),
        ),
        migrations.AddField(
            model_name='product',
            name='most_popular_brands',
            field=models.BooleanField(default=False, verbose_name=' محبوب\u200cترین برندها'),
        ),
        migrations.AddField(
            model_name='product',
            name='newest',
            field=models.BooleanField(default=False, verbose_name='جدید ترین محصولات '),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False, verbose_name=' پیشنهاد شگفت انگیز'),
        ),
    ]
