# Generated by Django 5.2 on 2025-09-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0035_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='most_popular_brands',
        ),
        migrations.RemoveField(
            model_name='product',
            name='newest',
        ),
    ]
