# Generated by Django 5.2 on 2025-09-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='weblog/', verbose_name='عکس ها')),
                ('madeby', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال یا غیرفعال؟')),
                ('is_delete', models.BooleanField(default=False, verbose_name='پاک بشه یا نا؟')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح کامل')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='url عنوان در ')),
            ],
            options={
                'verbose_name': 'وبلاگ',
                'verbose_name_plural': 'وبلاگ ها',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
