# Generated by Django 5.2 on 2025-09-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_order_address_order_city_order_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_date',
        ),
    ]
