# Generated by Django 5.2 on 2025-08-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='about_img',
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_img',
            field=models.ImageField(null=True, upload_to='about_img/', verbose_name='درباره ما عکس '),
        ),
    ]
