# Generated by Django 5.2 on 2025-08-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_remove_sitesetting_about_img_about_us_about_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='is_main_setting',
            new_name='is_main_about_us',
        ),
        migrations.RenameField(
            model_name='about_us_services',
            old_name='is_main_setting',
            new_name='is_main_about_us_services',
        ),
    ]
