# Generated by Django 5.2 on 2025-08-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_rename_is_main_setting_about_us_is_main_about_us_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_about', models.TextField(verbose_name='متن درباره ما فوتر')),
                ('instaLink', models.URLField(verbose_name='لینک اینستا')),
                ('whatsappLink', models.URLField(verbose_name='لینک واتساپ')),
                ('youtubeLink', models.URLField(verbose_name='لینک یوتوب')),
            ],
            options={
                'verbose_name': ' فوتر',
                'verbose_name_plural': ' فوتر',
            },
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider/', verbose_name='عکس اسلایدر'),
        ),
    ]
