# Generated by Django 5.2 on 2025-08-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_footer_alter_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
