# Generated by Django 5.2 on 2025-08-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_footer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinkbox',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
