# Generated by Django 5.2 on 2025-08-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='best_seller',
            field=models.BooleanField(null=True, verbose_name='محصولات پرفروش '),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hot',
            field=models.BooleanField(null=True, verbose_name=' داغ ترین چند ساعت گذشته'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='most_popular_brands',
            field=models.BooleanField(null=True, verbose_name=' محبوب\u200cترین برندها'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='newest',
            field=models.BooleanField(null=True, verbose_name='جدید ترین محصولات '),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='offer',
            field=models.BooleanField(null=True, verbose_name=' پیشنهاد شگفت انگیز'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='top_category',
            field=models.BooleanField(null=True, verbose_name='دسـته بندی هـای محبوب '),
        ),
    ]
