# Generated by Django 5.2 on 2025-08-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_sitesetting_best_seller_sitesetting_hot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='hot',
            field=models.BooleanField(blank=True, null=True, verbose_name=' داغ ترین چند ساعت گذشته'),
        ),
    ]
