# Generated by Django 5.2 on 2025-08-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0009_alter_sitesetting_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='best_seller',
            field=models.BooleanField(default=False, verbose_name='محصولات پرفروش '),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hot',
            field=models.BooleanField(default=False, verbose_name=' داغ ترین چند ساعت گذشته'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='is_main_setting',
            field=models.BooleanField(default=False, verbose_name='تنظیمات اصلی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='most_popular_brands',
            field=models.BooleanField(default=False, verbose_name=' محبوب\u200cترین برندها'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='newest',
            field=models.BooleanField(default=False, verbose_name='جدید ترین محصولات '),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='offer',
            field=models.BooleanField(default=False, verbose_name=' پیشنهاد شگفت انگیز'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='top_category',
            field=models.BooleanField(default=False, verbose_name='دسـته بندی هـای محبوب '),
        ),
    ]
