# Generated by Django 5.2 on 2025-09-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0010_alter_sitesetting_best_seller_alter_sitesetting_hot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='hot',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='most_popular_brands',
        ),
    ]
