# Generated by Django 5.2 on 2025-08-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='عنوان پیام')),
                ('phone_number', models.CharField(max_length=300, verbose_name='شماره تماس')),
                ('message', models.TextField(verbose_name='متن پیام مخاطب')),
                ('admin_message', models.TextField(verbose_name='پیام ادمین')),
                ('is_read_admin', models.BooleanField(default=False, verbose_name='خوانده شده / خوانده نشده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
