# Generated by Django 5.2 on 2025-08-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_remove_customuser_code_expiry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
    ]
