# Generated by Django 5.2 on 2025-08-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_rename_image_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
    ]
