# Generated by Django 5.2 on 2025-08-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_remove_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'کاربر سفارشی'},
        ),
    ]
